INSERT INTO exercise (name, muscle_group, equipment) VALUES
-- Chest
('Barbell Bench Press', 'CHEST', 'BARBELL'),
('Incline Barbell Bench Press', 'CHEST', 'BARBELL'),
('Dumbbell Bench Press', 'CHEST', 'DUMBBELL'),
('Incline Dumbbell Press', 'CHEST', 'DUMBBELL'),
('Smith Machine Bench Press', 'CHEST', 'SMITH_MACHINE'),
('Machine Chest Press', 'CHEST', 'MACHINE'),
('Cable Fly', 'CHEST', 'CABLE'),
('Dumbbell Fly', 'CHEST', 'DUMBBELL'),
('Pec Deck', 'CHEST', 'MACHINE'),
('Push-Up', 'CHEST', 'BODYWEIGHT_ONLY'),
('Chest Dip', 'CHEST', 'BODYWEIGHT_LOADABLE'),
-- Back
('Pull-Up', 'BACK', 'BODYWEIGHT_LOADABLE'),
('Chin-Up', 'BACK', 'BODYWEIGHT_LOADABLE'),
('Assisted Pull-Up', 'BACK', 'MACHINE_ASSISTANCE'),
('Lat Pulldown', 'BACK', 'CABLE'),
('Barbell Row', 'BACK', 'BARBELL'),
('Dumbbell Row', 'BACK', 'DUMBBELL'),
('Seated Cable Row', 'BACK', 'CABLE'),
('Machine Row', 'BACK', 'MACHINE'),
('Deadlift', 'BACK', 'BARBELL'),
('Back Extension', 'BACK', 'BODYWEIGHT_LOADABLE'),
-- Shoulders
('Overhead Press', 'SHOULDERS', 'BARBELL'),
('Dumbbell Shoulder Press', 'SHOULDERS', 'DUMBBELL'),
('Machine Shoulder Press', 'SHOULDERS', 'MACHINE'),
('Dumbbell Lateral Raise', 'SHOULDERS', 'DUMBBELL'),
('Cable Lateral Raise', 'SHOULDERS', 'CABLE'),
('Rear Delt Machine Fly', 'SHOULDERS', 'MACHINE'),
('Face Pull', 'SHOULDERS', 'CABLE'),
('Dumbbell Shrug', 'SHOULDERS', 'DUMBBELL'),
-- Biceps
('Barbell Curl', 'BICEPS', 'BARBELL'),
('Dumbbell Curl', 'BICEPS', 'DUMBBELL'),
('Hammer Curl', 'BICEPS', 'DUMBBELL'),
('Cable Curl', 'BICEPS', 'CABLE'),
('Machine Preacher Curl', 'BICEPS', 'MACHINE'),
-- Triceps
('Tricep Pushdown', 'TRICEPS', 'CABLE'),
('Overhead Cable Tricep Extension', 'TRICEPS', 'CABLE'),
('Skull Crusher', 'TRICEPS', 'BARBELL'),
('Close-Grip Bench Press', 'TRICEPS', 'BARBELL'),
('Tricep Dip', 'TRICEPS', 'BODYWEIGHT_LOADABLE'),
('Assisted Dip', 'TRICEPS', 'MACHINE_ASSISTANCE'),
-- Quads
('Barbell Back Squat', 'QUADS', 'BARBELL'),
('Front Squat', 'QUADS', 'BARBELL'),
('Smith Machine Squat', 'QUADS', 'SMITH_MACHINE'),
('Leg Press', 'QUADS', 'MACHINE'),
('Leg Extension', 'QUADS', 'MACHINE'),
('Hack Squat', 'QUADS', 'MACHINE'),
('Bulgarian Split Squat', 'QUADS', 'DUMBBELL'),
('Walking Lunge', 'QUADS', 'DUMBBELL'),
('Goblet Squat', 'QUADS', 'DUMBBELL'),
-- Hamstrings
('Romanian Deadlift', 'HAMSTRINGS', 'BARBELL'),
('Dumbbell Romanian Deadlift', 'HAMSTRINGS', 'DUMBBELL'),
('Lying Leg Curl', 'HAMSTRINGS', 'MACHINE'),
('Seated Leg Curl', 'HAMSTRINGS', 'MACHINE'),
-- Glutes
('Barbell Hip Thrust', 'GLUTES', 'BARBELL'),
('Machine Glute Kickback', 'GLUTES', 'MACHINE'),
('Cable Glute Kickback', 'GLUTES', 'CABLE'),
('Hip Abduction Machine', 'GLUTES', 'MACHINE'),
-- Calves
('Standing Calf Raise', 'CALVES', 'MACHINE'),
('Seated Calf Raise', 'CALVES', 'MACHINE'),
-- Core
('Plank', 'CORE', 'BODYWEIGHT_ONLY'),
('Hanging Leg Raise', 'CORE', 'BODYWEIGHT_ONLY'),
('Cable Crunch', 'CORE', 'CABLE'),
('Ab Wheel Rollout', 'CORE', 'BODYWEIGHT_ONLY'),
-- Full body
('Farmer Carry', 'FULL_BODY', 'DUMBBELL'),
('Burpee', 'FULL_BODY', 'BODYWEIGHT_ONLY'),
-- Cardio
('Treadmill Run', 'CARDIO', 'MACHINE'),
('Treadmill Walk', 'CARDIO', 'MACHINE'),
('Incline Treadmill Walk', 'CARDIO', 'MACHINE'),
('Stair Master', 'CARDIO', 'MACHINE'),
('Stationary Bike', 'CARDIO', 'MACHINE'),
('Elliptical', 'CARDIO', 'MACHINE'),
('Rowing Machine', 'CARDIO', 'MACHINE'),
('Outdoor Run', 'CARDIO', 'BODYWEIGHT_ONLY'),
('Outdoor Walk', 'CARDIO', 'BODYWEIGHT_ONLY'),
('Jump Rope', 'CARDIO', 'BODYWEIGHT_ONLY'),
('Swimming', 'CARDIO', 'BODYWEIGHT_ONLY');